### ISSUE TITLE
Problem about project hierarchy

### ISSUE THREAD

**Issue by reorx** [TuSDK/tusdk-face-go#1]
According to the import name `apidemo/api` in `demo.go`, it seems I have to put the code into `$GOPATH/src/apidemo/api` before running the demo. But normally people publish go project on github and import using the same path. So I think it's better to import `github.com/TuSDK/tusdk-face-go/api` in the demo, in this way user can install the project by `go get -u github.com/TuSDK/tusdk-face-go`

**Comment by idealhack** [comment]
d51d33a fixes this issue, thanks 😃
